version: '3.9'

services:
  backend:
    build: .
    container_name: backend
    expose:
      - "8000"
    environment:
      - DB_URL=jdbc:mysql://db:3300/mysql?
      - DB_USERNAME=root
      - DB_PASSWORD=123
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "81:81"
    depends_on:
      - backend
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3300:3300"
    volumes:
      - ./core:/app/var/lib/mysql
    labels:
      org.springframework.boot.jdbc.parameters: "ssl=true&sslmode=require"