CREATE TABLE  `fuel_station` (
                                 `zone_id` VARCHAR(2),
                                 `area_id` VARCHAR(4),
                                 `city_id` VARCHAR(4),
                                 `code` VARCHAR(5),
                                 `id` VARCHAR(4) NOT NULL,
                                 `name` VARCHAR(100),
                                 `type` CHAR(1),
                                 `address` VARCHAR(500),
                                 `incharge_man` VARCHAR(50),
                                 `email` VARCHAR(20),
                                 `contact_man` VARCHAR(50),
                                 `contact_telephone` VARCHAR(20),
                                 `telephone1` VARCHAR(20),
                                 `telephone2` VARCHAR(20),
                                 `fax` VARCHAR(20),
                                 `zip_code` VARCHAR(10),
                                 `open_date` TIMESTAMP,
                                 `init_count` NUMERIC (5, 0),
                                 `dialup_sign` CHAR(1),
                                 `dailysettle_begin` VARCHAR(6),
                                 `dailysettle_end` VARCHAR(6),
                                 `owner` VARCHAR(30),
                                 `init_status` CHAR(1),
                                 `validity` CHAR(1),
                                 CONSTRAINT `PK_fuel_station` PRIMARY KEY (`id`)
);

CREATE TABLE `fuel_terminal` (
                                 `fuel_station_id` VARCHAR(4) NOT NULL,
                                 `id` VARCHAR(2) NOT NULL,
                                 `fuel_sam_id` VARCHAR(15),
                                 `pay_sam_id` VARCHAR(15),
                                 `fuel_type` VARCHAR(2),
                                 `ipc_ip_addr` VARCHAR(2),
                                 `pt_ip_addr` VARCHAR(20),
                                 `nozzle_id` VARCHAR(2),
                                 `oilcan_id` VARCHAR(2),
                                 `dispenser_type` VARCHAR(2),
                                 `f_fuel_public_key_n` VARCHAR(256),
                                 `f_pay_public_key_n` VARCHAR(256),
                                 `s_fuel_public_key_n` VARCHAR(256),
                                 `s_pay_public_key_n` VARCHAR(256),
                                 `f_fuel_public_key_e` VARCHAR(8),
                                 `f_pay_public_key_e` VARCHAR(8),
                                 `s_fuel_public_key_e` VARCHAR(8),
                                 `s_pay_public_key_e` VARCHAR(8),
                                 `init_status` CHAR(1),
                                 `f_cardissue_status` CHAR(1),
                                 `p_cardissue_status` CHAR(1),
                                 `app_issuer` VARCHAR(16),
                                 `app_receiver` VARCHAR(16),
                                 `app_date_begin` TIMESTAMP,
                                 `app_date_end` TIMESTAMP,
                                 `st_app_issuer` VARCHAR(16),
                                 `st_app_receiver` VARCHAR(16),
                                 `st_app_date_begin` TIMESTAMP,
                                 `st_app_date_end` TIMESTAMP,
                                 `sam_seria` VARCHAR(20),
                                 `sam_ver` VARCHAR(2),
                                 `card_type` VARCHAR(2),
                                 `fci_by_issuer` VARCHAR(4),
                                 `con_key_idx` VARCHAR(2),
                                 `f_batch_name` VARCHAR(20),
                                 `p_batch_name` VARCHAR(20),
                                 `apply_time` TIMESTAMP,
                                 `validity` CHAR(1),
                                 CONSTRAINT `PK_fuel_terminal` PRIMARY KEY (`fuel_station_id`, `id`),
                                 CONSTRAINT `FK_fuel_station` FOREIGN KEY (`fuel_station_id`)
                                     REFERENCES `fuel_station` (`id`)
                                     ON DELETE NO ACTION ON UPDATE NO ACTION
);
